### ISSUE TITLE
Hito 1: 3 KPI’s

### ISSUE THREAD

**Issue by lmunozm1702** [lmunozm1702/taxi_electrico_nyc#11]

**Comment by FranciscoHugoLezik** [comment]
Primer KPI de tipo Proceso: Incrementar un 10 % por año:
Porcentaje de Cambios de Motor = Numero de vehículos convertidos a eléctricos en un año / Total de vehículos híbridos en un año anterior x 100

Segundo KPI de tipo Return On Investment (ROI): Incrementar un 20 %:
Retorno = (Totales de pasajeros que usaron el servicio - Inversión total en autos) / Inversión total en autos.

Tercer KPI de tipo Runway:  Durar 6 meses sin ingresos o ingresos insuficientes:
Tiempo de vida sin ingresos = Dinero disponible ÷ Gastos mensuales totales. (Expresado en meses).

**Comment by FranciscoHugoLezik** [comment]
Primer KPI:
Aumentar la cantidad de vehículos híbridos que son reemplazados por vehículos eléctricos en un trimestre.

Segundo KPI: 
Aumentar el numero de carros eléctricos o híbridos activos por trimestre.

Tercer KPI:
Aumentar la cantidad de viajes por trimestre en un determinado borough.

**Comment by FranciscoHugoLezik** [comment]
Primer KPI:
Aumentar la cantidad de vehículos híbridos que son reemplazados por vehículos eléctricos en un trimestre.

Segundo KPI:
Aumentar el numero de carros eléctricos o híbridos activos por trimestre.

Tercer KPI:
Aumentar la cantidad de viajes por trimestre en un determinado borough.

Cuarto KPI (CO2):

Quinto KPI (Contaminación sonora):

**Comment by FranciscoHugoLezik** [comment]
Primer KPI:
Aumentar la cantidad de vehículos híbridos que son reemplazados por vehículos eléctricos en un trimestre.

Segundo KPI:
Aumentar el numero de carros eléctricos o híbridos activos por trimestre.

Tercer KPI:
Aumentar la cantidad de viajes por trimestre en un determinado borough.

Cuarto KPI:
Reducción de los tiempos en solicitud de la carrera y el momento de recoger al pasajero.

Quinto KPI (CO2):

Sexto KPI (Contaminación sonora):

**Comment by FranciscoHugoLezik** [comment]
Primer KPI:
Aumentar la cantidad de vehículos híbridos que son reemplazados por vehículos eléctricos en un trimestre.

Segundo KPI:
Aumentar el numero de carros eléctricos o híbridos activos por trimestre.

Tercer KPI:
Aumentar la cantidad de viajes por trimestre en un determinado borough.

Cuarto KPI:
Reducción de los tiempos en solicitud de la carrera y el momento de recoger al pasajero.
