### ISSUE TITLE
Correlación de datos EDA Etapa 2

### ISSUE THREAD

**Issue by juanka94** [lmunozm1702/taxi_electrico_nyc#93]
Buscar correlacion de datos & insights.

**Comment by Samuel-R-021** [comment]
Completado el EDA de correlaciones.
El principal insight es que la data presenta estacionalidad cuando se mide a lo largo de las horas del día.
Se sugiere al equipo de ML que considere la data a la hora de seleccionar y entrenar el modelo como una serie de tiempo.
